# Generated by Django 5.1.4 on 2025-01-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
        migrations.AddField(
            model_name='goal',
            name='scope',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='timeline',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('flexible', 'Flexible')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
