# Generated by Django 5.1.4 on 2025-01-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
